# Generated by Django 3.1.5 on 2021-01-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_01', '0002_auto_20210113_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='departamento_id',
            new_name='departamento',
        ),
    ]
