# Generated by Django 3.1.5 on 2021-01-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_01', '0003_auto_20210117_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='departamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='migrate_01.departamento'),
        ),
    ]
